// This file isn't used by default.
// This contains 1,000+ keywords.
// Blocks some posts.
// Use at your own risk
const DEFAULT_KEYWORDS = [
  "doge", "dogecoin", "elon", "musk", "elon musk", "grok", "politics", "political", "trump", "maga",
  "politician", "political scandal", "political controversy", "government", "federal government",
  "us government", "administration", "bureaucracy", "government takeover", "government efficiency",
  "cost-cutting", "budget cuts", "federal layoffs", "mass firings", "administrative layoffs",
  "political purge", "political shakeup", "political corruption", "government fraud", "donald trump",
  "president trump", "trump admin", "trump 2024", "trump administration", "trump conspiracy",
  "trump scandal", "trump derangement", "musk 2024", "musk takeover", "musk derangement", "elon takeover",
  "tesla mogul", "spacex", "musk admin", "doge meme", "to the moon", "d.o.g.e",
  "department of government efficiency", "grok ai", "chatgpt vs grok", "grok censorship", "r/the_donald",
  "r/politics", "r/whitepeopletwitter", "neo-nazi", "far-right", "alt-right", "political extremist",
  "white supremacist", "efficiency commission", "government audit", "trump coup", "political takeover",
  "government purge", "dismantle bureaucracy", "deep state", "cronyism", "conflict of interest",
  "political lawsuit", "ukraine", "palestine", "isreal", "protesters", "protest", "genocide", "immigrants",
  "illegals", "luigi mangione", "jon stewart", "oligarchy", "joe", "joe biden", "us president", "u.s. president",
  "tesla", "teslas", "tesla's", 'judge declines', 'judge refuses', 'grook', 'gok', 'billioniare', 'billionaires',
  'republican', 'democrat', 'democracy', 'republicans', 'vote yes', 'vote no', 'voted yes', 'voted no', 'economy',
  'grifter', 'grifters', 'terrorist', 'bomb', 'bomber', 'bombers', 'terrorists', 'white house', 'supreme', 'supreme court',
  'court', 'cdc', 'halts', 'vaccination', 'vaccines', 'vaccine', 'campaign', 'congress', 'deputized', 'shocking moment',
  'gold bar', 'defrauding', 'inflation', 'immigration', 'conservative', 'maggot', 'maggots', 'gulf', 'cia', 'disenfranchise',
  'votes', 'vote', 'fbi', 'standoff', 'tax', "Trump's", 'Project 2025', 'governor', 'abortion', 'ban', 'measles', 'U.S.', 'outbreak',
  'golfing', 'Exclusion', 'American', 'America', 'Nazi', 'Salute', 'Griok', 'what if you were lied to', 'howard', 'lutnick', 'what to know about',
  'we the people', '🇺🇸', 'somber', 'disintegrates', 'ukrainian', 'power grab', 'executive', 'orders', 'germany', '1933', 'john mccain', 'strike', 'against',
  'country', 'destroyed', 'federal', 'employees', 'jobs', 'full-time', 'full time', 'part-time', 'part time', 'weak', 'strongman', 'unfreedom', 'timothy snyder',
  'slava', 'ukraini', 'president-trump', 'impeach', 'truth', 'james comey', 'agent', 'agents', 'investigate', 'prosecute', 'inaugural', 'FDR', 'memorial', 'Bernie',
  "Bernie's", 'tan', 'peace', 'treaty', 'law', 'legislation', '1992', 'kyiv', 'victims', 'treasury', 'secretary', 'mnuchin', 'woodstock', 'sheriff', 'bob norris',
  'investigation', 'conduct', 'dan crenshaw', 'f--king', 'tucker carlson', 'distressing', 'concerning', 'breaking news', 'Gabbard',
  'Intelligence Officers', 'plummets', 'decline', 'Pete Hegseth', 'Reporter', 'Underqualified', 'Military', 'Chief', 'Business license',
  'Coeur d’Alene', 'town hall dragging incident', 'Upside-Down US', 'Upside Down US', 'Distress', 'prohibited', 'foreign', 'slavery', 'slave', 'labor',
  'Invasive', 'frisks', 'suicide', 'migrants', 'Guantánamo', 'detention', 'Mike Johnson', 'holdouts', 'passes budget framework', 'steep cuts', 'calling for',
  'FDA', 'Pfizer', 'Dem', 'gop', 'Same-Sex', 'same sex', 'Josh Schriver', 'rachel', 'maddow', 'let go', 'overhaul', 'overthrow', 'dismantle', '3.5 percent', '3.5%',
  'medicaid', 'shortfalls', 'USAID', 'overdue', 'bills', 'ashley judd', 'traffickers', 'trafficker', 'trafficked', '9news.com', 'half-staff', 'Rep.', 'Sudan',
  'IDR', 'student loan', 'student loans', 'egg prices', 'egg price', 'price of eggs', 'cost of eggs', 'IED', 'weapons', 'shouting', 'new bill', 'bill', 'rights',
  'freedom of speech', 'civil rights', 'rights', 'mental health', 'gaza', 'ceasefire', 'NIST', 'AI Safety', 'prepares to cut', 'cut', 'dismisses', 'report', 'ousted',
  'five eyes', 'rudy', 'guiliani', 'judgement', 'fulton', 'county', 'election', 'workers', 'mass firing', 'servicemembers', 'FFRF', 'bible-in-school', 'unconstitutional',
  'Boston', 'The City of', 'Tom Homan', 'Security Bag', 'musical act', 'disinvited', 'Kennedy Center', 'Skepticism Is Not Science', 'Hegseth',
  'JAGs', 'Army', 'Navy', 'Air Force', 'layoff', 'layoffs', 'fear', 'concern', 'legislative', "Coeur d'Alene", 'chaos', 'Right-Wing', 'Populism',
  'Denmark’s', 'Denmark', 'Liberals', 'Liberal', 'Speak Up', 'VA', 'Health Care', 'Gutted', 'Andrew', 'Cuomo', 'mayor', 'USDA', 'scholarship', 'scholarships',
  'suspended', 'MSNBC', 'Joy Reid', "Joy Reid's", 'major', 'shakeup', 'bigotry', 'transgender', 'bans', 'outlines', 'Kamala', 'Harris', 'Electrifies',
  'NAACP', 'Chairman’s Award', ' | ', 'prison', 'bodycams', 'closures', 'left', 'embrance', 'ICE', 'purge', 'generals', 'initiatives', "'White' House", "Paula",
  'Resegregation', 'MTG', 'Racist', 'Obama', 'Enrique', 'Tarrio', 'US Capitol', 'US', 'U.S', 'January 6', 'Eric Adams', 'Andrew Cuomo', 'dependence',
  'Europe’s', 'all part of the plan', "2A",
  "9/11 inside job",
  "911 truth",
  "ACAB",
  "ACA",
  "AfD",
  "Affordable Care Act",
  "Agenda 21",
  "Agenda21",
  "Alec Jones",
  "Alex Jones",
  "Alexander Lukashenko",
  "Al Qaeda",
  "Al-Qaeda",
  "All Lives Matter",
  "Allende",
  "Amerikkka",
  "Amy Coney Barrett",
  "Angela Alsobrooks",
  "Angela Merkel",
  "Angus King",
  "Antifa",
  "Antonin Scalia",
  "Arab Spring",
  "Area 51",
  "Arizona audit",
  "Aryan Nation",
  "Assange",
  "Assault weapons ban",
  "Azov Battalion",
  "BLM",
  "BLM Plaza",
  "Babylon Bee",
  "Bacon's rebellion",
  "Baldwin, Tammy",
  "Banana republic",
  "Barack Obama",
  "Barak Obama",
  "Barry Soetoro",
  "Barry Goldwater",
  "Bashar al-Assad",
  "Bengazi",
  "Benghazi",
  "Benito Mussolini",
  "Benjamin Netanyahu",
  "Bernie Sanders",
  "Berniecrat",
  "Big Pharma",
  "Big Tech",
  "Birther",
  "Birtherism",
  "Black Helicopters",
  "Black Lives Matter",
  "Black Panther Party",
  "Black helicopter",
  "Black helicopters",
  "Blackwater",
  "Blue Lives Matter",
  "Bohemian Grove",
  "Boko Haram",
  "Bolsonaro",
  "Boris Johnson",
  "Boycott",
  "Brexit",
  "Brexit Party",
  "Brezhnev",
  "Britt, Katie Boyd",
  "Brothers of Italy",
  "Budapest memorandum",
  "Budapest Memorandum",
  "Build Back Better",
  "Build the wall",
  "Burn Loot Murder",
  "Bush Jr",
  "Bush Sr",
  "Bush, George H.W.",
  "Bush, George W.",
  "Buzynski, Nikki",
  "CHAZ",
  "CHOP",
  "COVID hoax",
  "COVID-19",
  "COVID19",
  "CRT",
  "Calexit",
  "Cambridge Analytica",
  "Capitol",
  "Capitol Hill",
  "Capitol Police",
  "Capitol insurrection",
  "Capitol riot",
  "Capitalism",
  "Capitalist",
  "Caracas",
  "Carbon tax",
  "Carrie Lam",
  "Carter",
  "Carter Page",
  "Carter, Jimmy",
  "Castro",
  "Catholic Church scandal",
  "Censorship",
  "Charlottesville",
  "Charlottesville riot",
  "Charlottesville rally",
  "Cheney",
  "Cheney, Dick",
  "Chemtrail",
  "Chemtrails",
  "China",
  "China virus",
  "Chinese Communist Party",
  "Chloroquine",
  "Chris Cuomo",
  "Christian Right",
  "Citadel",
  "Citizens United",
  "Clinton",
  "Clinton Body Count",
  "Clinton Foundation",
  "Clinton, Bill",
  "Clinton, Chelsea",
  "Clinton, Hillary",
  "Cliven Bundy",
  "Cold War",
  "Colin Kaepernick",
  "Colin Powell",
  "Comey",
  "Communism",
  "Communist",
  "Communist Party",
  "Comrade",
  "Concealed carry",
  "Confederacy",
  "Confederate",
  "Confederate flag",
  "Conservative Party",
  "Conservatives",
  "Conspiracy",
  "Constitution",
  "Constitutional crisis",
  "Controversial",
  "Convoy",
  "Coup",
  "Covfefe",
  "Critical Race Theory",
  "Crooked Hillary",
  "Cruz, Ted",
  "Cuban Missile Crisis",
  "Czech Republic protests",
  "DJT",
  "DNC",
  "DPRK",
  "Deep State",
  "Deep state",
  "Deepfake",
  "Defund the police",
  "Delaware",
  "Democracy",
  "Democrat",
  "Democrats",
  "Democratic National Committee",
  "Democratic Party",
  "Demoncrats",
  "Demonrats",
  "Deplorables",
  "Deplatforming",
  "Dictator",
  "Dictatorship",
  "Dinesh D'Souza",
  "Diosdado Cabello",
  "Disinformation",
  "Division",
  "Dogecoin",
  "Donald Drumpf",
  "Donald J Trump",
  "Donald John Trump",
  "Donald Norcross",
  "Donald Trump",
  "Donald Trum",
  "Donald Trump Jr",
  "Donald Trump Jr.",
  "Donald Trunp",
  "Donal Trump",
  "Don't Ask Don't Tell",
  "Don't Say Gay",
  "Drain the swamp",
  "Dreamer",
  "Dreamers",
  "Duckworth, Tammy",
  "Dumbocrat",
  "Durbin, Richard J.",
  "ENRON",
  "Earth is flat",
  "Easter worshippers",
  "Election",
  "Election fraud",
  "Elizabeth Warren",
  "End of the world",
  "End times",
  "Energy crisis",
  "Epstein",
  "Epstein didn't kill himself",
  "Epstein, Jeffrey",
  "Eric Trump",
  "Ethnonationalism",
  "Eugenics",
  "Evita",
  "Executive order",
  "FBI",
  "FJB",
  "FISA",
  "FISA court",
  "FISA warrant",
  "FLDS",
  "FLOTUS",
  "False flag",
  "Far-left",
  "Far-right",
  "Fascism",
  "Fascist",
  "Faucigate",
  "Federal Reserve",
  "Federalist Society",
  "Feminazi",
  "Fiat currency",
  "First Amendment",
  "Flight 93",
  "Florida Man",
  "Fox News",
  "Frazzledrip",
  "Freemason",
  "Freemasons",
  "Freepers",
  "Freedom Caucus",
  "Freedom Convoy",
  "Freedom Party",
  "GME",
  "GOP",
  "GOPe",
  "Gab",
  "Gabrielle Giffords",
  "Gamergate",
  "Gavin Newsom",
  "George Floyd",
  "George H.W. Bush",
  "George Soros",
  "George W Bush",
  "George W. Bush",
  "Georgia Guidestones",
  "Gerald Ford",
  "Glenn Beck",
  "Global elites",
  "Globalist",
  "Globalists",
  "Global warming",
  "Great Awakening",
  "Great Replacement",
  "Great Reset",
  "Greta Thunberg",
  "Green Party",
  "Green new deal",
  "Green New Deal",
  "H.R. 1",
  "HHS",
  "Hamas",
  "Hands up don't shoot",
  "Harvey Weinstein",
  "Hate crime",
  "Hate speech",
  "Hawaii",
  "Hezbollah",
  "Hillary Clinton",
  "Hilary Clinton",
  "Hitler",
  "Hitlery",
  "Holocaust",
  "Holocaust denial",
  "Holodomor",
  "Hong Kong protests",
  "Hoover",
  "Hosni Mubarak",
  "Hunter Biden",
  "Hunter Biden's laptop",
  "IAEA",
  "ICE",
  "IRS",
  "IDF",
  "ILLUMINATI",
  "Immigration",
  "Impeach",
  "Impeachment",
  "Indictment",
  "Influence peddling",
  "Iraq War",
  "Islamic State",
  "Israel",
  "Israel animal spying",
  "Israhell",
  "Ivermectin",
  "Jack Ma",
  "Jacky Rosen",
  "Jacob Zuma",
  "Jair Bolsonaro",
  "Jamal Khashoggi",
  "James Comey",
  "James O'Keefe",
  "James, Lindsey",
  "Jared Kushner",
  "Jason Kenney",
  "Jeff Bezos",
  "Jeff Sessions",
  "Jefferson Davis",
  "Jerusalem",
  "Jesse Jackson",
  "Jewish space laser",
  "Jim Banks",
  "Jim Crow",
  "Jim Jordan",
  "Jimmy Carter",
  "Joe Biden",
  "Joe Rogan",
  "John Birch Society",
  "John Bolton",
  "John F Kennedy",
  "John F. Kennedy",
  "John Kerry",
  "John McCain",
  "John Roberts",
  "John, King",
  "Joseph Stalin",
  "Joshua Wong",
  "Julian Assange",
  "Justin Trudeau",
  "Kamala Harris",
  "Kamala Haris",
  "Karl Marx",
  "Kavanaugh",
  "Kenosha",
  "Keystone XL",
  "Killary",
  "Kim Jong Il",
  "Kim Jong Un",
  "Kim regime",
  "Kim, Andy",
  "King, Angus",
  "Kinzinger, Adam",
  "Kissinger",
  "Klaus Schwab",
  "Klobuchar, Amy",
  "Kremlin",
  "Kurdish",
  "Kurds",
  "Kuomintang",
  "Ku Klux Klan",
  "Kurdish genocide",
  "Kyrsten Sinema",
  "Kyiv",
  "LENIN",
  "LOL",
  "LSAT",
  "Laffer curve",
  "LatinX",
  "Lavrentiy Beria",
  "Law and order",
  "Lebron James",
  "Leon Trotsky",
  "Lesbian",
  "Liberal Democrats",
  "Liberal snowflake",
  "Libertarian Party",
  "Libertarians",
  "Lindsey Graham",
  "Lizard people",
  "Lock Her Up",
  "Lois Lerner",
  "Lone wolf",
  "Los Zetas",
  "Louis DeJoy",
  "Luis Arce",
  "Lula",
  "Luxembourg",
  "MAGAzine",
  "MAGA",
  "MH17",
  "MH370",
  "Malala Yousafzai",
  "Mar-a-Lago",
  "Marcy Kaptur",
  "Margaret Thatcher",
  "Marjorie Taylor Greene",
  "Mark Meadows",
  "Mark Pocan",
  "Mark Zuckerberg",
  "Marxism",
  "Marxist",
  "Mass shooting",
  "Matt Gaetz",
  "Media Matters",
  "Medicare for All",
  "Mercer family",
  "Merrick Garland",
  "Michael Avenatti",
  "Michael Cohen",
  "Michael Flynn",
  "Michelle Obama",
  "Mike Pence",
  "Mike Pompeo",
  "Mike Pence",
  "Monica Lewinsky",
  "Montana militia",
  "Moscow Mitch",
  "Mueller Report",
  "Mueller investigation",
  "Muhammad",
  "Muhammad al-Baghdadi",
  "Muslim ban",
  "Muslim Brotherhood",
  "My Pillow Guy",
  "NAMBLA",
  "NSA",
  "NFT",
  "NRA",
  "NSDAP",
  "Name calling",
  "Nancy Pelosi",
  "National Guard",
  "Nationalism",
  "Nazis",
  "Nazism",
  "Nazis",
  "Net Neutrality",
  "Netherlands riot",
  "NeverTrump",
  "New Coke",
  "New World Order",
  "Newsmax",
  "Nikki Haley",
  "Nixon",
  "No justice no peace",
  "North Korea",
  "Not My President",
  "OANN",
  "Obama",
  "Obamacare",
  "Obamagate",
  "Occasional Cortex",
  "Occupy",
  "Occupy Central",
  "Occupy Wall Street",
  "Ocasio-Cortez",
  "Ocasio",
  "October Surprise",
  "Oligarchy",
  "Open carry",
  "Oath Keepers",
  "Operation Paperclip",
  "Oregon standoff",
  "Osama bin Laden",
  "Osama bin Ladin",
  "OxyContin",
  "PLO",
  "PTSD",
  "Paddock, Stephen",
  "Panama Papers",
  "Pandora Papers",
  "Parler",
  "Patriot Act",
  "Patriot Front",
  "Patriot Prayer",
  "Patriotism",
  "Paul Manafort",
  "Paul Ryan",
  "Pauline Hanson",
  "Peaceful protest",
  "Pence",
  "Pepe",
  "Pepe the Frog",
  "Peter Thiel",
  "Philadelphia Eagles protest",
  "Piglosi",
  "Pizzagate",
  "Planned Parenthood",
  "Planned parenthood",
  "Plutocracy",
  "Pocahontas",
  "Police brutality",
  "Pope Francis",
  "Populism",
  "Populist",
  "Pork barrel",
  "Portland protests",
  "Proud Boys",
  "Putin",
  "QAnon",
  "Q Anon",
  "Q-Anon",
  "Qanon",
  "Queer",
  "Radical left",
  "Radical right",
  "Rand Paul",
  "Rashida Tlaib",
  "Raskin, Jamie",
  "Rasmussen poll",
  "Ravensbrück",
  'blue states',
  'red states',
  "Raytheon",
  "Rbg",
  "Red pill",
  "Redpilled",
  "Reichstag",
  "Religious freedom",
  "Religious right",
  "Remainer",
  "Rent boycott",
  "Reparations",
  "Republican",
  "Republican National Committee",
  "Republicans",
  "Resistance",
  "Revolution",
  "Richard Spencer",
  "Rigged election",
  "Roger Stone",
  "Rolling coal",
  "Ron DeSantis",
  "Roswell",
  "Roe vs Wade",
  "Roe v. Wade",
  "Roe v Wade",
  "Royal family",
  "Ruby Ridge",
  "Rudy Giuliani",
  "Russiagate",
  "SJW",
  "SOPA",
  "Saddam Hussein",
  "Same-sex marriage",
  "Sandy Hook",
  "Sarah Palin",
  "Sarin gas",
  "Satellite state",
  "Saul Alinsky",
  "Say her name",
  "Scamdemic",
  "Sean Hannity",
  "Section 230",
  "Second Amendment",
  "Sedition",
  "Senate",
  "Senator",
  "September 11",
  "Sharia",
  "Sheeple",
  "Shelter in place",
  "Sheriff Joe",
  "Shillary",
  "Shinzo Abe",
  "Shooting",
  "Slick Willy",
  "Slotkin, Elissa",
  "Smollet hoax",
  "Snowflake",
  "Social Justice Warrior",
  "Socialism",
  "Socialist",
  "Solyndra",
  "Sons of Liberty",
  "Soros",
  "Southern strategy",
  "Sovereign citizen",
  "Soy boy",
  "Spain protests",
  "Special prosecutor",
  "Spygate",
  "Stacey Abrams",
  "Standing Rock",
  "State Department",
  "Statue removal",
  "Steve Bannon",
  "Steven Mnuchin",
  "Stonewall",
  "Stop the count",
  "Stop the steal",
  "Stormfront",
  "Straight Pride",
  "Sudan protests",
  "Super PAC",
  "Supreme Court",
  "Surveillance",
  "Sustainable",
  "Swamp",
  "TPUSA",
  "TX",
  "Taiwan independence",
  "Tammy Baldwin",
  "Tammy Duckworth",
  "Tax cuts",
  "Tea Party",
  "Ted Cruz",
  "Ted Kaczynski",
  "Ted Lieu",
  "Texas secession",
  "The Squad",
  "The Swamp",
  "The Donald",
  "Theresa May",
  "Thin blue line",
  "Thomas Massie",
  "Thurgood Marshall",
  "Tiananmen",
  "Tibet",
  "Tierney",
  "Tim Scott",
  "Timothy McVeigh",
  "Tom Cotton",
  "Tony Blair",
  "Trilateral Commission",
  "Trotsky",
  "Tucker Carlson",
  "Tulsi Gabbard",
  "TulsiGabbard",
  "Turkey coup",
  "Twilight Zone election",
  "Twitter Files",
  "Ukraine",
  "UN",
  "USSR",
  "USA",
  "USA PATRIOT Act",
  "USMCA",
  "Uber",
  "Uncle Tom",
  "Unemployment",
  "Unite the Right",
  "United Nations",
  "Universal basic income",
  "University protest",
  "Vaccine microchip",
  "Vegan agenda",
  "Venezuela crisis",
  "Vladimir Putin",
  "Vote rigging",
  "Voting rights",
  "WWG1WGA",
  "Wall Street",
  "WallStreetBets",
  "War on Drugs",
  "War on Terror",
  "War protest",
  "Warnock, Raphael",
  "Washington establishment",
  "Watergate",
  "We Build The Wall",
  "Weinstein",
  "White House",
  "White supremacy",
  "White nationalist",
  "Whitehouse, Sheldon",
  "WikiLeaks",
  "Woke",
  "Women's March",
  "Xi Jinping",
  "Xinjiang",
  "Yellow Vest",
  "Zelensky",
  "Zelenskyy",
  "Zionism",
  "Zionist",
  "Zucc"
];

function hidePostIfMatch(post) {
  let combinedText = "";
  const titleEl = post.querySelector("[slot='title'], a[data-testid='post-title'], h1, h3");
  if (titleEl) {
    combinedText += titleEl.textContent.toLowerCase();
  }
  const descEl = post.querySelector("[slot='text-body']");
  if (descEl) {
    combinedText += " " + descEl.textContent.toLowerCase();
  }
  for (const keyword of DEFAULT_KEYWORDS) {
    if (combinedText.includes(keyword.toLowerCase())) {
      post.classList.add("reddit-filter-hidden");
      break;
    }
  }
}

function processNewNode(node) {
  if (node.nodeType !== Node.ELEMENT_NODE) return;
  if (node.matches("shreddit-post, div[data-testid='post-container']")) {
    hidePostIfMatch(node);
  }
  const subPosts = node.querySelectorAll?.("shreddit-post, div[data-testid='post-container']");
  subPosts?.forEach(hidePostIfMatch);
}

function initObserver() {
  new MutationObserver(mutations => {
    for (const mutation of mutations) {
      for (const addedNode of mutation.addedNodes) {
        processNewNode(addedNode);
      }
    }
  }).observe(document.documentElement, { childList: true, subtree: true });
}

(function () {
  if (document.body) {
    document.querySelectorAll("shreddit-post, div[data-testid='post-container']").forEach(hidePostIfMatch);
    initObserver();
  } else {
    document.addEventListener("DOMContentLoaded", () => {
      document.querySelectorAll("shreddit-post, div[data-testid='post-container']").forEach(hidePostIfMatch);
      initObserver();
    });
  }
})();
